// Copyright 2020-2025 Tecdrop SRL. All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found
// in the LICENSE file or at https://www.tecdrop.com/tapguid/license/.
//
// Flutter icons CustomIcons
// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.

/// Custom icons used in the app.
library;

import 'package:flutter/widgets.dart';

const _kFontFam = 'CustomIcons';
const String? _kFontPkg = null;

/// The GitHub mark icon from Octicons.
const IconData github = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
